---
align:
    runMode: alignReads
    genomeDir: /cluster/projects/carlsgroup/workinprogress/abdel/20170418_INSPIRE_RNA/STARIndex_hg38_gencode_genomeSAsparseD2/
    runThreadN: 4
    chimSegmentMin: 20
    readFilesCommand: zcat
    twopassMode: Basic
    outSAMprimaryFlag: AllBestScore
    outFilterIntronMotifs: RemoveNoncanonical
    outSAMtype: BAM SortedByCoordinate
    quantMode: TranscriptomeSAM GeneCounts
    outSAMunmapped: Within
    genomeSAsparseD: 2
    limitBAMsortRAM: 35000000000

fusion:
    chimeric_function:
    chimeric_out_sam:
    ref_GTF: /cluster/projects/carlsgroup/workinprogress/abdel/20170418_INSPIRE_RNA//gencode.v26.annotation.gtf
    out_prefix:
